Fixed coding style issues and adding input checks to functions
b-cubed-eu/pdindicatoR pull request #41
Opened 2024-12-04 10:58 UTC by LBreugelmans

- [ ] make output of generate_pd_map_and_indicator() silent in readme to avoid showing personal folder path
- [ ] fix #33 
- [ ] add input checks to start of functions
- [ ] update version
- [ ] run codemeta
- [ ] assign reviewer

2024-12-09 09:16 UTC, wlangera requested changes
Hi

Thanks for the fast work.
There are some small comments, often because you have more than 80 characters on one line.

It is not really good practice to have all these if statements, this increases the [cyclomatic complexity](https://www.geeksforgeeks.org/cyclomatic-complexity/). There is a  `stopifnot()` function and the assertthat package also has some good functions. In[ the guidelines](https://www.geeksforgeeks.org/cyclomatic-complexity/) they have other recommendations.
I will make a branch with an example. Your choice if you implement this.

I have updated the package version in the zenodo file

2024-12-09 09:16 UTC, wlangera commented on R/calculate_FaithPD.R
> +#' @param mrca_node_id Node id of the taxon that represents the most recent common
lines should not be more than 80 characters, this line is 82

2024-12-09 09:16 UTC, wlangera commented on R/calculate_FaithPD.R
> +
Trailing blank lines are superfluous (2 witregels op einde van R script mogen weg)

2024-12-09 09:16 UTC, wlangera commented on R/generate_map_and_indicator.R
> +                  "protected areas is", round(indicators$Overall, digits=2), "%"))
```suggestion
                  "protected areas is", round(indicators$Overall, digits = 2), "%"))
```

2024-12-09 09:16 UTC, wlangera commented on R/generate_map_and_indicator.R
> +                  "protected areas is", round(indicators$Overall, digits=2), "%"))
Lines should not be more than 80 characters

2024-12-09 09:16 UTC, wlangera commented on R/get_pd_cube.R
> +  if (!metric %in% available_metrics){stop("The selected PD metric is not available.")}
```suggestion
stopifnot("The selected PD metric is not available." = metric %in% available_metrics)
```

2024-12-09 09:16 UTC, wlangera commented on R/get_pd_cube.R
> +                                    ~ calculate_faithpd(tree, unlist(.x), mrca_node_id))
lines should not be more than 80 characters

2024-12-09 09:16 UTC, wlangera commented on R/retrieve_example_data.R
> +    matched_nona = function(path) read.csv(path, stringsAsFactors = FALSE, sep = ",")
lines should not be more than 80 characters

2024-12-09 09:16 UTC, wlangera commented on R/retrieve_example_data.R
> +    cube = function(path) utils::read.csv(path, stringsAsFactors = FALSE, sep = "\t"),
lines should not be more than 80 characters

2024-12-09 09:23 UTC, wlangera commented on R/aggregate_cube.R
> +  if (!is.data.frame(mcube)) {
stopifnot("Error: 'mcube' must be a dataframe or tibble." =
              inherits(mcube, "data.frame"))

2024-12-09 09:30 UTC, wlangera commented on R/generate_map_and_indicator.R
> +  if (!"CELLCODE" %in% colnames(grid)) {
stopifnot (and assertthat):

stopifnot("`grid` must contain a column named 'CELLCODE' for grid cell codes." = assertthat::has_name(grid, "CELLCODE"))

2024-12-09 09:31 UTC, wlangera commented
Please run `devtools::document()` and `codemetar::write_codemeta()` after your changes

2025-04-11 10:20 UTC, LBreugelmans commented on R/generate_map_and_indicator.R
> +  if (!"CELLCODE" %in% colnames(grid)) {
Doublecheck other functions for similar use

2025-04-14 08:47 UTC, wlangera reviewed
Hi, please have a look at my final PR [here](https://github.com/b-cubed-eu/pdindicatoR/pull/49).

I fixed some  minor coding style things, and a file name to lower letters.
I also bumped the version to 0.1.0 because the whole pull request is rather large.
No big changes.

If you agree with that PR, we can merge with main :)

2025-04-15 09:45 UTC, wlangera approved these changes

2025-04-15 09:59 UTC, merged